### ISSUE TITLE
Attributes changing case

### ISSUE THREAD

**Issue by Zennii** [holygits/casey#10]
Currently the crate will case attributes such as `repr` and `derive`, which isn't ideal. For example:

```rust
macro_rules! test {
    ($($name:ident),*) => {
        #[repr(usize)]
        #[derive(PartialEq, Debug, Copy, Clone)]
        casey::pascal!(
            pub enum Test {
                $($name,)*
            }
        );
    }
}

test! {
    one,
    two,
    three
}

```

This will give the desired enum, but will error out on the attributes, so instinctually I included them inside `casey::pascal` like this:

```rust
macro_rules! test {
    ($($name:ident),*) => {
        casey::pascal!(
            #[repr(usize)]
            #[derive(PartialEq, Debug, Copy, Clone)]
            pub enum Test {
                $($name,)*
            }
        );
    }
}
```

and they do expand, just not correctly. They will expand to this:

```rust
#[Repr(usize)]
#[Derive(PartialEq, Debug, Copy, Clone)]
pub enum Test {
    One,
    Two,
    Three,
}
```

Note that `repr` and `derive` are now pascal case, which now results in an entirely new error as rust can't handle that.

Currently the workaround for me is to write my items in pascal case and use `lower!` instead. Which works but is a little bit awkward.

Is there another way to do this? Or perhaps it can be supported?

**Comment by jordy25519** [comment]
hi,
thanks for reporting this!
it makes sense to skip transforming attribute macros so should be able to write:
```rust
        casey::pascal!(
            #[repr(usize)]
            #[derive(PartialEq, Debug, Copy, Clone)]
            pub enum Test {
                $($name,)*
            }
        );
```
without any issues after #11 is merged (published as `0.4.0` on crates.io)
